scoreboard objectives add unlinked.essentials.ore_coal dummy
scoreboard objectives add unlinked.essentials.ore_redstone dummy
scoreboard objectives add unlinked.essentials.ore_copper dummy
scoreboard objectives add unlinked.essentials.ore_iron dummy
scoreboard objectives add unlinked.essentials.ore_gold dummy
scoreboard objectives add unlinked.essentials.ore_quartz dummy
scoreboard objectives add unlinked.essentials.ancient_debris dummy
scoreboard objectives add unlinked.essentials.ore_emerald dummy
scoreboard objectives add unlinked.essentials.ore_lapis dummy
scoreboard objectives add unlinked.essentials.ore_diamond dummy
scoreboard objectives add unlinked.essentials.ancient_debris dummy
 
scoreboard players add @s unlinked.essentials.ore_coal 0
scoreboard players add @s unlinked.essentials.ore_redstone 0
scoreboard players add @s unlinked.essentials.ore_copper 0
scoreboard players add @s unlinked.essentials.ore_iron 0
scoreboard players add @s unlinked.essentials.ore_gold 0
scoreboard players add @s unlinked.essentials.ore_quartz 0
scoreboard players add @s unlinked.essentials.ancient_debris 0
scoreboard players add @s unlinked.essentials.ore_emerald 0
scoreboard players add @s unlinked.essentials.ore_lapis 0
scoreboard players add @s unlinked.essentials.ore_diamond 0
scoreboard players add @s unlinked.essentials.ancient_debris 0
 
playsound unlinked.essentials.scan @a ~ ~ ~
 
 
 
tag @s[rxm=50,rx=90] add unlinked.domino_miner.down
tag @s[rxm=-90,rx=-50] add unlinked.domino_miner.up
tag @s[rym=-45,ry=45,rxm=-50,rx=50] add unlinked.domino_miner.north
tag @s[rym=-135,ry=-45,rxm=-50,rx=50] add unlinked.domino_miner.east
tag @s[rym=-180,ry=-135,rxm=-50,rx=50] add unlinked.domino_miner.south
tag @s[rym=45,ry=135,rxm=-50,rx=50] add unlinked.domino_miner.west
tag @s[rym=135,ry=180,rxm=-50,rx=50] add unlinked.domino_miner.south
 
execute as @s[tag=unlinked.domino_miner.south] run particle ulkd_ess:essentials1 ~ ~1.5 ~-1
execute as @s[tag=unlinked.domino_miner.south] run particle ulkd_ess:essentials1 ~ ~1.5 ~-2
execute as @s[tag=unlinked.domino_miner.south] run particle ulkd_ess:essentials1 ~ ~1.5 ~-3
execute as @s[tag=unlinked.domino_miner.south] run particle ulkd_ess:essentials1 ~ ~1.5 ~-4
execute as @s[tag=unlinked.domino_miner.south] run particle ulkd_ess:essentials1 ~ ~1.5 ~-5
execute as @s[tag=unlinked.domino_miner.south] run particle ulkd_ess:essentials1 ~ ~1.5 ~-6
execute as @s[tag=unlinked.domino_miner.south] run particle ulkd_ess:essentials1 ~ ~1.5 ~-7
execute as @s[tag=unlinked.domino_miner.south] run particle ulkd_ess:essentials1 ~ ~1.5 ~-8
execute as @s[tag=unlinked.domino_miner.south] run particle ulkd_ess:essentials1 ~ ~1.5 ~-9
execute as @s[tag=unlinked.domino_miner.south] run particle ulkd_ess:essentials1 ~ ~1.5 ~-10
execute as @s[tag=unlinked.domino_miner.north] run particle ulkd_ess:essentials2 ~ ~1.5 ~1
execute as @s[tag=unlinked.domino_miner.north] run particle ulkd_ess:essentials2 ~ ~1.5 ~2
execute as @s[tag=unlinked.domino_miner.north] run particle ulkd_ess:essentials2 ~ ~1.5 ~3
execute as @s[tag=unlinked.domino_miner.north] run particle ulkd_ess:essentials2 ~ ~1.5 ~4
execute as @s[tag=unlinked.domino_miner.north] run particle ulkd_ess:essentials2 ~ ~1.5 ~5
execute as @s[tag=unlinked.domino_miner.north] run particle ulkd_ess:essentials2 ~ ~1.5 ~6
execute as @s[tag=unlinked.domino_miner.north] run particle ulkd_ess:essentials2 ~ ~1.5 ~7
execute as @s[tag=unlinked.domino_miner.north] run particle ulkd_ess:essentials2 ~ ~1.5 ~8
execute as @s[tag=unlinked.domino_miner.north] run particle ulkd_ess:essentials2 ~ ~1.5 ~9
execute as @s[tag=unlinked.domino_miner.north] run particle ulkd_ess:essentials2 ~ ~1.5 ~10
execute as @s[tag=unlinked.domino_miner.east] run particle ulkd_ess:essentials3 ~1 ~1.5 ~
execute as @s[tag=unlinked.domino_miner.east] run particle ulkd_ess:essentials3 ~2 ~1.5 ~
execute as @s[tag=unlinked.domino_miner.east] run particle ulkd_ess:essentials3 ~3 ~1.5 ~
execute as @s[tag=unlinked.domino_miner.east] run particle ulkd_ess:essentials3 ~4 ~1.5 ~
execute as @s[tag=unlinked.domino_miner.east] run particle ulkd_ess:essentials3 ~5 ~1.5 ~
execute as @s[tag=unlinked.domino_miner.east] run particle ulkd_ess:essentials3 ~6 ~1.5 ~
execute as @s[tag=unlinked.domino_miner.east] run particle ulkd_ess:essentials3 ~7 ~1.5 ~
execute as @s[tag=unlinked.domino_miner.east] run particle ulkd_ess:essentials3 ~8 ~1.5 ~
execute as @s[tag=unlinked.domino_miner.east] run particle ulkd_ess:essentials3 ~9 ~1.5 ~
execute as @s[tag=unlinked.domino_miner.east] run particle ulkd_ess:essentials3 ~10 ~1.5 ~
execute as @s[tag=unlinked.domino_miner.west] run particle ulkd_ess:essentials4 ~-1 ~1.5 ~
execute as @s[tag=unlinked.domino_miner.west] run particle ulkd_ess:essentials4 ~-2 ~1.5 ~
execute as @s[tag=unlinked.domino_miner.west] run particle ulkd_ess:essentials4 ~-3 ~1.5 ~
execute as @s[tag=unlinked.domino_miner.west] run particle ulkd_ess:essentials4 ~-4 ~1.5 ~
execute as @s[tag=unlinked.domino_miner.west] run particle ulkd_ess:essentials4 ~-5 ~1.5 ~
execute as @s[tag=unlinked.domino_miner.west] run particle ulkd_ess:essentials4 ~-6 ~1.5 ~
execute as @s[tag=unlinked.domino_miner.west] run particle ulkd_ess:essentials4 ~-7 ~1.5 ~
execute as @s[tag=unlinked.domino_miner.west] run particle ulkd_ess:essentials4 ~-8 ~1.5 ~
execute as @s[tag=unlinked.domino_miner.west] run particle ulkd_ess:essentials4 ~-9 ~1.5 ~
execute as @s[tag=unlinked.domino_miner.west] run particle ulkd_ess:essentials4 ~-10 ~1.5 ~
execute as @s[tag=unlinked.domino_miner.down] run particle ulkd_ess:essentials5 ~ ~-1 ~
execute as @s[tag=unlinked.domino_miner.down] run particle ulkd_ess:essentials5 ~ ~-2 ~
execute as @s[tag=unlinked.domino_miner.down] run particle ulkd_ess:essentials5 ~ ~-3 ~
execute as @s[tag=unlinked.domino_miner.down] run particle ulkd_ess:essentials5 ~ ~-4 ~
execute as @s[tag=unlinked.domino_miner.down] run particle ulkd_ess:essentials5 ~ ~-5 ~
execute as @s[tag=unlinked.domino_miner.down] run particle ulkd_ess:essentials5 ~ ~-6 ~
execute as @s[tag=unlinked.domino_miner.down] run particle ulkd_ess:essentials5 ~ ~-7 ~
execute as @s[tag=unlinked.domino_miner.down] run particle ulkd_ess:essentials5 ~ ~-8 ~
execute as @s[tag=unlinked.domino_miner.down] run particle ulkd_ess:essentials5 ~ ~-9 ~
execute as @s[tag=unlinked.domino_miner.down] run particle ulkd_ess:essentials5 ~ ~-10 ~
execute as @s[tag=unlinked.domino_miner.up] run particle ulkd_ess:essentials6 ~ ~1 ~
execute as @s[tag=unlinked.domino_miner.up] run particle ulkd_ess:essentials6 ~ ~2 ~
execute as @s[tag=unlinked.domino_miner.up] run particle ulkd_ess:essentials6 ~ ~3 ~
execute as @s[tag=unlinked.domino_miner.up] run particle ulkd_ess:essentials6 ~ ~4 ~
execute as @s[tag=unlinked.domino_miner.up] run particle ulkd_ess:essentials6 ~ ~5 ~
execute as @s[tag=unlinked.domino_miner.up] run particle ulkd_ess:essentials6 ~ ~6 ~
execute as @s[tag=unlinked.domino_miner.up] run particle ulkd_ess:essentials6 ~ ~7 ~
execute as @s[tag=unlinked.domino_miner.up] run particle ulkd_ess:essentials6 ~ ~8 ~
execute as @s[tag=unlinked.domino_miner.up] run particle ulkd_ess:essentials6 ~ ~9 ~
execute as @s[tag=unlinked.domino_miner.up] run particle ulkd_ess:essentials6 ~ ~10 ~
 
 
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-3 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-3 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-3 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-3 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-3 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-3 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-3 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-3 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-3 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-4 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-4 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-4 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-4 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-4 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-4 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-4 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-4 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-4 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-5 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-5 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-5 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-5 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-5 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-5 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-5 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-5 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-5 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-6 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-6 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-6 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-6 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-6 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-6 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-6 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-6 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-6 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-7 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-7 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-7 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-7 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-7 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-7 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-7 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-7 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-7 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-8 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-8 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-8 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-8 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-8 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-8 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-8 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-8 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-8 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-9 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-9 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-9 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-9 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-9 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-9 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-9 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-9 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-9 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-10 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-10 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-10 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-10 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~ ~-10 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-10 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-10 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~1 ~-10 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.down] if block ~-1 ~-10 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1


execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~10 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~10 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~10 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~10 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~10 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~10 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~10 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~10 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~10 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~9 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~9 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~9 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~9 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~9 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~9 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~9 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~9 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~9 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~8 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~8 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~8 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~8 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~8 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~8 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~8 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~8 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~8 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~7 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~7 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~7 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~7 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~7 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~7 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~7 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~7 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~7 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~6 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~6 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~6 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~6 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~6 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~6 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~6 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~6 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~6 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~5 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~5 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~5 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~5 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~5 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~5 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~5 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~5 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~5 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~4 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~4 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~4 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~4 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~4 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~4 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~4 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~4 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~4 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~3 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~3 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~3 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~3 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~3 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~3 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~3 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~3 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~3 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~ ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~1 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.up] if block ~-1 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~1 ~2 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~1 ~2 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~1 ~2 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~2 ~2 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~2 ~2 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~2 ~2 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~ ~2 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~ ~2 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~ ~2 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~1 ~3 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~1 ~3 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~1 ~3 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~2 ~3 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~2 ~3 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~2 ~3 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~ ~3 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~ ~3 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~ ~3 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~1 ~4 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~1 ~4 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~1 ~4 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~2 ~4 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~2 ~4 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~2 ~4 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~ ~4 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~ ~4 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~ ~4 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~1 ~5 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~1 ~5 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~1 ~5 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~2 ~5 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~2 ~5 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~2 ~5 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~ ~5 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~ ~5 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~ ~5 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~1 ~6 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~1 ~6 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~1 ~6 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~2 ~6 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~2 ~6 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~2 ~6 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~ ~6 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~ ~6 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~ ~6 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~1 ~7 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~1 ~7 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~1 ~7 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~2 ~7 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~2 ~7 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~2 ~7 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~ ~7 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~ ~7 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~ ~7 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~1 ~8 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~1 ~8 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~1 ~8 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~2 ~8 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~2 ~8 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~2 ~8 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~ ~8 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~ ~8 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~ ~8 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~1 ~9 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~1 ~9 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~1 ~9 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~2 ~9 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~2 ~9 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~2 ~9 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~ ~9 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~ ~9 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~ ~9 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~1 ~10 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~1 ~10 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~1 ~10 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~2 ~10 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~2 ~10 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~2 ~10 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~1 ~ ~10 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~ ~ ~10 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.north] if block ~-1 ~ ~10 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1


execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~1 ~-2 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~1 ~-2 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~1 ~-2 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~2 ~-2 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~2 ~-2 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~2 ~-2 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~ ~-2 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~ ~-2 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~ ~-2 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~1 ~-3 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~1 ~-3 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~1 ~-3 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~2 ~-3 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~2 ~-3 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~2 ~-3 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~ ~-3 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~ ~-3 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~ ~-3 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~1 ~-4 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~1 ~-4 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~1 ~-4 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~2 ~-4 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~2 ~-4 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~2 ~-4 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~ ~-4 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~ ~-4 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~ ~-4 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~1 ~-5 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~1 ~-5 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~1 ~-5 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~2 ~-5 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~2 ~-5 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~2 ~-5 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~ ~-5 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~ ~-5 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~ ~-5 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~1 ~-6 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~1 ~-6 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~1 ~-6 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~2 ~-6 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~2 ~-6 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~2 ~-6 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~ ~-6 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~ ~-6 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~ ~-6 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~1 ~-7 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~1 ~-7 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~1 ~-7 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~2 ~-7 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~2 ~-7 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~2 ~-7 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~ ~-7 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~ ~-7 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~ ~-7 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~1 ~-8 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~1 ~-8 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~1 ~-8 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~2 ~-8 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~2 ~-8 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~2 ~-8 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~ ~-8 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~ ~-8 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~ ~-8 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~1 ~-9 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~1 ~-9 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~1 ~-9 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~2 ~-9 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~2 ~-9 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~2 ~-9 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~ ~-9 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~ ~-9 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~ ~-9 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~1 ~-10 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~1 ~-10 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~1 ~-10 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~2 ~-10 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~2 ~-10 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~2 ~-10 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~1 ~ ~-10 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~ ~ ~-10 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.south] if block ~-1 ~ ~-10 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1


execute as @s[tag=unlinked.domino_miner.east] if block ~1 ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~1 ~ ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~1 ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~1 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~1 ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~1 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~1 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~1 ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~1 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~2 ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~2 ~ ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~2 ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~2 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~2 ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~2 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~2 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~2 ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~2 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~3 ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~3 ~ ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~3 ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~3 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~3 ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~3 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~3 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~3 ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~3 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~4 ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~4 ~ ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~4 ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~4 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~4 ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~4 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~4 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~4 ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~4 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~5 ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~5 ~ ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~5 ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~5 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~5 ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~5 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~5 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~5 ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~5 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~6 ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~6 ~ ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~6 ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~6 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~6 ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~6 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~6 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~6 ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~6 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~7 ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~7 ~ ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~7 ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~7 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~7 ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~7 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~7 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~7 ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~7 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~8 ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~8 ~ ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~8 ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~8 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~8 ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~8 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~8 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~8 ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~8 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~9 ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~9 ~ ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~9 ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~9 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~9 ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~9 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~9 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~9 ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~9 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~10 ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~10 ~ ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~10 ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~10 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~10 ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~10 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~10 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~10 ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.east] if block ~10 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1


execute as @s[tag=unlinked.domino_miner.west] if block ~-1 ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-1 ~ ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-1 ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-1 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-1 ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-1 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-1 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-1 ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-1 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-2 ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-2 ~ ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-2 ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-2 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-2 ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-2 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-2 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-2 ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-2 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-3 ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-3 ~ ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-3 ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-3 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-3 ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-3 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-3 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-3 ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-3 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-4 ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-4 ~ ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-4 ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-4 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-4 ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-4 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-4 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-4 ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-4 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-5 ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-5 ~ ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-5 ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-5 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-5 ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-5 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-5 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-5 ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-5 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-6 ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-6 ~ ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-6 ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-6 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-6 ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-6 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-6 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-6 ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-6 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-7 ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-7 ~ ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-7 ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-7 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-7 ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-7 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-7 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-7 ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-7 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-8 ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-8 ~ ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-8 ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-8 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-8 ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-8 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-8 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-8 ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-8 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-9 ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-9 ~ ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-9 ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-9 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-9 ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-9 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-9 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-9 ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-9 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-10 ~ ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-10 ~ ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-10 ~ ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-10 ~1 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-10 ~1 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-10 ~1 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-10 ~2 ~1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-10 ~2 ~ ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
execute as @s[tag=unlinked.domino_miner.west] if block ~-10 ~2 ~-1 ancient_debris run scoreboard players add @s unlinked.essentials.ancient_debris 1
 
tag @s remove unlinked.domino_miner.down
tag @s remove unlinked.domino_miner.up
tag @s remove unlinked.domino_miner.north
tag @s remove unlinked.domino_miner.east
tag @s remove unlinked.domino_miner.south
tag @s remove unlinked.domino_miner.west